# Generated by Django 5.1.1 on 2024-09-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (1, 'OEM Admin'), (2, 'OEM User'), (3, 'Dealer Admin'), (4, 'Dealer User'), (5, 'Customer')], default=5),
        ),
    ]
