# Generated by Django 5.1.1 on 2024-09-16 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_dealer_oem_customuser_dealer_dealer_oem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='permitted_users',
        ),
        migrations.AddField(
            model_name='book',
            name='permitted_customers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 5}, related_name='customer_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='permitted_dealers',
            field=models.ManyToManyField(blank=True, related_name='allowed_books', to='books.dealer'),
        ),
        migrations.AddField(
            model_name='book',
            name='permitted_oems',
            field=models.ManyToManyField(blank=True, related_name='allowed_books', to='books.oem'),
        ),
    ]
