# Generated by Django 5.1.1 on 2024-09-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_permitted_users_book_permitted_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='permitted_customers',
        ),
        migrations.RemoveField(
            model_name='book',
            name='permitted_dealers',
        ),
        migrations.RemoveField(
            model_name='book',
            name='permitted_oems',
        ),
    ]
