# Generated by Django 5.1.1 on 2024-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_permitted_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
